name: 'Terraform Apply'

on:
  #push:
  #  branches:
  #   - main
  
  workflow_dispatch:
    inputs:
      trigger:
        description: "apply OR destroy"
        required: true
        default: apply
        type: choice
        options:
        - apply
        - destroy

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: eu-central-1
  TF_CLOUD_ORGANIZATION: "dkorobenko"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "learning-terraform"
  CONFIG_DIRECTORY: "./"
  TRIGGER: '${{ inputs.trigger }}'

jobs:
  create-ecr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
    
      - name: Upload Configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0
        id: apply-upload
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          directory: ${{ env.CONFIG_DIRECTORY }}
      - name: Create Apply Run
        if: env.TRIGGER == 'apply'
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.0
        id: apply-run
        with:
          workspace: ${{ env.TF_WORKSPACE }}
      - name: Apply
        if: env.TRIGGER == 'apply'
        uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.0.0
        id: apply
        with:
          run: ${{ steps.apply-run.outputs.run_id }}
          comment: "Apply Run from GitHub Actions CI ${{ github.sha }}"
      - name: Destroy
        if: env.TRIGGER == 'apply'
        run:
            terraform destroy -auto-approve